<?php
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Archivematica Connector'), 1, $this->translate('Past Imports')); ?>
<?php if (empty($imports)): ?>
<div class="no-resources">
    <p><?php echo $this->translate('There are no past imports.'); ?></p>
</div>
<?php else: ?>
<?php echo $this->pagination(); ?>

<form method='POST'>
    <fieldset id='page-actions'>
        <input type='submit' value="<?php echo $this->translate('Submit'); ?>" />
    </fieldset>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $escape($this->translate('Undo')); ?></th>
                <th><?php echo $escape($this->translate('Job ID')); ?></th>
                <th><?php echo $escape($this->translate('File')); ?></th>
                <th><?php echo $escape($this->translate('Comment')); ?></th>
                <th><?php echo $escape($this->translate('Items')); ?></th>
                <th><?php echo $escape($this->translate('Date')); ?></th>
                <th><?php echo $escape($this->translate('Status')); ?></th>
                <th><?php echo $escape($this->translate('Owner')); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($imports as $import): ?>
        <?php $job = $import->job(); $undoJob = $import->undoJob(); ?>
        <tr>
            <td>
                <?php if (!$undoJob): ?>
                <input type='checkbox' name='undoJobs[]' value='<?php echo $job->id(); ?>' aria-label="<?php echo $this->translate('Undo job'); ?>" />
                <?php endif; ?>
            </td>
            <td><?php echo $job->link($job->id()); ?></td>
            <td>
                <?php
                $args = $job->args();
                echo $escape($args['original_filename'] ?? '—');
                ?>
            </td>
            <td><?php echo $escape($import->comment()); ?></td>
            <td>
                <?php
                $liveCount = $this->api()->search('items', ['archivematica_import_id' => $job->id()])->getTotalResults();
                if ($liveCount > 0) {
                    echo $this->hyperlink('Total: ' . $liveCount, $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['archivematica_import_id' => $job->id()]]), ['target' => '_blank']) . '<br>';
                } else {
                    echo 'Total: ' . ($import->addedCount() + $import->updatedCount()) . '<br>';
                }
                echo 'Added: ' . $import->addedCount() . '<br>';
                echo 'Updated: ' . $import->updatedCount();
                ?>
            </td>
            <td><?php echo $escape($this->i18n()->dateFormat($job->started())); ?></td>
            <td>
            <?php
            if ($undoJob) {
                echo $this->translate('Undone in job ') . $undoJob->id() . ': ' . $escape($this->i18n()->dateFormat($undoJob->ended()));
            } else {
                echo $this->translate($job->status());
            }
            ?>
            </td>
            <td><?php echo $this->hyperlink($job->owner()->name(), $this->url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $job->owner()->id()])); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</form>
<?php endif; ?>
